# Generated by Django 5.2.2 on 2025-07-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_pay',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
