# Generated by Django 5.2.8 on 2025-12-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('receptionist', 'Recepcionista'), ('user', 'Usuario')], default='user', max_length=20),
        ),
    ]
