# Generated by Django 5.2.3 on 2025-08-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='membership_duration',
        ),
        migrations.AddField(
            model_name='membership',
            name='duration_membership',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='status_membership',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='offers_membership',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='price_membership',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
