# Generated by Django 5.2.8 on 2025-11-18 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50, verbose_name='Género')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('condition', models.CharField(max_length=100, verbose_name='Padecimiento/Condición')),
                ('goal', models.CharField(max_length=100, verbose_name='Objetivo Fitness')),
                ('experience', models.CharField(max_length=50, verbose_name='Nivel de Experiencia')),
                ('duration', models.CharField(max_length=50, verbose_name='Duración del Entrenamiento Deseada')),
                ('fitness_level', models.CharField(default='beginner', max_length=50, verbose_name='Nivel de Fitness Calculado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Cliente')),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfiles de Clientes',
            },
        ),
    ]
