# Generated by Django 5.2.3 on 2025-06-18 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sales_product_name_remove_sales_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='price',
        ),
    ]
