# Generated by Django 5.2.3 on 2025-06-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sales_id_products_sales_created_at_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
