# Generated by Django 5.2.2 on 2025-07-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0006_sales_user_sales_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='items',
            field=models.ManyToManyField(related_name='items', through='sales.SaleItem', to='products.product'),
        ),
    ]
