# Generated by Django 5.2.2 on 2025-08-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sales_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
