# Generated by Django 5.2.2 on 2025-08-08 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0009_remove_sales_user_name_alter_sales_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='sales.sales'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='items',
            field=models.ManyToManyField(related_name='sales_items', through='sales.SaleItem', to='products.product'),
        ),
    ]
