# Generated by Django 5.2.2 on 2025-08-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_remove_sales_items_remove_sales_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='total_price',
        ),
    ]
