# Generated by Django 5.2.2 on 2025-08-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_saleitem_total_price_sales_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='total_price',
        ),
    ]
