# Generated by Django 5.2.2 on 2025-08-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_saleitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='total_price',
        ),
    ]
