# Generated by Django 5.2.2 on 2025-08-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_remove_saleitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
