# Generated by Django 5.2.8 on 2025-12-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routina',
            name='Description',
            field=models.TextField(default='', max_length=50, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='routina',
            name='Times_done',
            field=models.IntegerField(default=0),
        ),
    ]
