# Generated by Django 5.2.8 on 2025-12-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_routina_description_routina_times_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Ejercicio')),
                ('description', models.TextField(verbose_name='Descripción del Ejercicio')),
                ('duration_seconds', models.IntegerField(verbose_name='Duración (segundos)')),
                ('repetitions', models.IntegerField(verbose_name='Repeticiones por Serie')),
                ('series', models.IntegerField(verbose_name='Series Recomendadas')),
                ('muscle_group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Músculo o Grupo trabajados')),
                ('recommended_level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=50, verbose_name='Nivel de Ejercicio')),
                ('Health_condition', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Lesión leve', 'Lesión leve'), ('problemas cardíacos', 'problemas cardíacos'), ('otro', 'otro')], default='Ninguno', max_length=50, verbose_name='Condicion de salud')),
                ('goal_type', models.CharField(choices=[('perder grasa', 'Perder Grasa'), ('Aumentar masa muscular', 'Aumentar masa muscular'), ('resistencia', 'Resistencia'), ('Mantenerme', 'Mantenerme')], max_length=100, verbose_name='Objetivo Compatible')),
            ],
        ),
        migrations.AddField(
            model_name='routina',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='routines', to='routines.exercise', verbose_name='Ejercicios de la Rutina'),
        ),
    ]
