# Generated by Django 5.2.8 on 2025-12-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_exercise_routina_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='goal_type',
            field=models.CharField(choices=[('Perder grasa', 'Perder Grasa'), ('Aumentar masa muscular', 'Aumentar masa muscular'), ('Resistencia', 'Resistencia'), ('Mantenerme', 'Mantenerme')], max_length=100, verbose_name='Objetivo Compatible'),
        ),
    ]
