# Generated by Django 5.2.8 on 2025-12-08 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_alter_exercise_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinehistory',
            name='Date_realization',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
